"""Shared strategy interfaces, contracts, and signal models."""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Protocol


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    NONE = "NONE"


@dataclass(frozen=True)
class Candle:
    """Represents a single OHLCV candlestick."""
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    @property
    def is_bullish(self) -> bool:
        return self.close > self.open

    @property
    def is_bearish(self) -> bool:
        return self.close < self.open

    @property
    def body_size(self) -> float:
        return abs(self.close - self.open)

    @property
    def total_range(self) -> float:
        return self.high - self.low


@dataclass(frozen=True)
class StrategySignal:
    """Trade signal generated by the strategy on a confirmed bar."""
    symbol: str
    signal_type: SignalType
    entry_price: float
    suggested_sl: float
    candle_time: datetime
    reason: str


class Strategy(Protocol):
    """Protocol for strategy implementations."""

    def evaluate(self, candles: list[Candle], symbol: str) -> StrategySignal | None:
        """Evaluate recent candles and return a StrategySignal if pattern confirms."""
        ...
